name: ESLint PR review

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rpkak/ESLint-PR-review@latest
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          src: src
          eslint-format: table
